apiVersion: cosmos.strange.love/v1alpha1
kind: HostedSnapshot
metadata:
  name: hostedsnapshot-sample
spec:
  # optional
  interval: 24h
  # required
  selector:
    target: value
  # optional
  jobTemplate:
    activeDeadlineSeconds: 3600
    backoffLimit: 1
    ttlSecondsAfterFinished: 30
  # required
  podTemplate:
    spec:
      containers:
      - name: test
        image: busybox:stable
        command:
          - ls
        args:
          - "/home/operator/cosmos"
  # required
  volumeClaimTemplate:
    storageClassName: premium-rwo
    accessModes:
      - ReadWriteOnce
