apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  # name should be the chain name
  name: cosmoshub
spec:
  replicas: 3
  chain:
    chainID: gaia
    binary: gaiad
    config: # Tendermint config (translates to config.toml)
      externalAddress: "p2p.example.com"
      peers: "peer@example.com:26656,peer2@example.com:26656"
      seeds: "seed@example.com:26656"
      maxInboundPeers: 10
      maxOutboundPeers: 10
    app: # Cosmos SDK config (translates to app.toml)
      minGasPrice: "0.0025uatom"
  template:
    image: "busybox:stable"
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "0.75"
  volumeClaimTemplate:
    # If testing on GKE, change to standard-rwo
    storageClassName: "standard" 
    resources:
      requests:
        storage: 100Mi
      
  
