# Optimized for GKE
apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  # Name should be the chain name and network environment.
  name: cosmoshub-mainnet
spec:
  replicas: 2
  chain:
    network: mainnet
    chainID: cosmoshub-4
    binary: gaiad
    skipInvariants: true
    genesisURL: "https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz"
    # Get latest snapshot at: https://www.polkachu.com/tendermint_snapshots/cosmos
    snapshotURL: "https://snapshots1.polkachu.com/snapshots/cosmos/cosmos_11701512.tar.lz4"
    # CometBFT config (translates to config.toml)
    config:
      peers: "ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,538ebe0086f0f5e9ca922dae0462cc87e22f0a50@34.122.34.67:26656,d3209b9f88eec64f10555a11ecbf797bb0fa29f4@34.125.169.233:26656,bdc2c3d410ca7731411b7e46a252012323fbbf37@34.83.209.166:26656"
      seeds: "cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656"
    # Cosmos SDK config (translates to app.toml)
    app:
      minGasPrice: "0.0025uatom"
  podTemplate:
    image: "ghcr.io/strangelove-ventures/heighliner/gaia"
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "1"
  volumeClaimTemplate:
    storageClassName: "standard-rwo"
    resources:
      requests:
        storage: 100Gi
      
  
